version: '3'
services:
  petclinic:
    image: springcommunity/spring-petclinic-rest
    entrypoint:
      - java
      - "-Dspring.datasource.url=jdbc:mysql://mysql:3306/petclinic"
      - "-Dspring.datasource.username=petclinic"
      - "-cp"
      - "/app/resources:/app/classes:/app/libs/*"
      - "org.springframework.samples.petclinic.PetClinicApplication"
    ports:
      - "9966:9966"
    environment:
      - "SPRING_PROFILES_ACTIVE=mysql,spring-data-jpa"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=pc
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
